### ISSUE TITLE
CSSO / docs / description / description.en.md

### ISSUE THREAD

**Issue by t32k** [enja-oss/CSSO#1]
2.2. Order of properties
Stick to the same order of properties throughout the stylesheet - it will allow you to not use the guards. The less manual intervention there is, the easier it is for the minimizer to work optimally.

上記の箇所ですが、意味が読み取れませんでした。
 the guardsってなんでしょうか？

**Comment by studiomohawk** [comment]
元々ロシア語のドキュメントを英語に翻訳しているだけあって、英文はだいぶ怪しげです。
まったく読めないロシア語の原文のほうも見てみましたが、[プログラム言語的なガード](http://ja.wikipedia.org/wiki/%E3%82%AC%E3%83%BC%E3%83%89_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0)ではなさそうです。

前後の文章から見て、"it will allow you to not use the guards" は説明的な意味合いしか持たないと考えられるので、
とりあえず省略してしまって、原書、あるいは、英訳者に確認したほうがいいと思います。

<ins>英訳者であるLeonid Khachaturov氏にメールにて質問しておきました。結果があればこちらで報告します。</ins>

**Comment by t32k** [comment]
ですよね。。連絡ありがとうございます！

**Comment by t32k** [comment]
CSSO開発やめっちゃったみたいなので。
